baseURL = 'https://verseaitech.netlify.app/'
languageCode = 'en-us'
title = 'VerseAI' # You can change this later if you like
theme = "PaperMod"
enableRobotsTXT = true

[related]
  threshold = 80
  includeNewer = true
  toLower = false
  [[related.indices]]
    name = "tags"
    weight = 100
  [[related.indices]]
    name = "date"
    weight = 10

[params]
  showRelatedPosts = true

  [params.analytics.google]
    SiteVerificationTag = "tTFePePTVUz-epm5EFBd4HWNO0qcC3chb-7mM7UMlWs"
