baseURL = 'https://verseaitech.netlify.app/'
languageCode = 'en-us'
title = 'VerseAI' # You can change this later if you like
theme = "PaperMod"
enableRobotsTXT = true

[related]
  threshold = 80
  includeNewer = true
  toLower = false
  [[related.indices]]
    name = "tags"
    weight = 100
  [[related.indices]]
    name = "date"
    weight = 10

# Define only the taxonomies you are using
[taxonomies]
  tag = "tags"
  # By explicitly defining taxonomies and omitting 'category',
  # Hugo will disable the default 'category' taxonomy.

[sitemap]
  # Set priority to -1 to effectively exclude taxonomy list pages
  [sitemap.taxonomies]
    tag = -1

[params]
  description = "Exploring the latest in AI and technology." # Site default meta description
  showRelatedPosts = true

  [params.analytics.google]
    SiteVerificationTag = "tTFePePTVUz-epm5EFBd4HWNO0qcC3chb-7mM7UMlWs"
